[gmail]
source            = imaps://bowen951209%40gmail.com@imap.gmail.com:993
outgoing          = smtps://bowen951209%40gmail.com@smtp.gmail.com:465
default           = INBOX
from              = Bowen Ho <bowen951209@gmail.com>
copy-to           = [Gmail]/寄件備份
postpone          = [Gmail]/草稿
cache-headers     = true
source-cred-cmd   = pass show gmail
outgoing-cred-cmd = pass show gmail

[nchu]
source            = imaps://s114062121@mail.nchu.edu.tw:993
outgoing          = smtps+login://s114062121@mail.nchu.edu.tw:465
default           = INBOX
from              = Bowen Ho <s114062121@mail.nchu.edu.tw>
copy-to           = 寄件備份匣
postpone          = Drafts
cache-headers     = true
source-cred-cmd   = pass show nchu
outgoing-cred-cmd = pass show nchu

[disroot]
source        = imaps://bowen95%40disroot.org@disroot.org:993
outgoing      = smtp://bowen95%40disroot.org@disroot.org:465
default       = INBOX
from          = Bowen Ho <bowen95@disroot.org>
copy-to       = Sent
cache-headers = true
source-cred-cmd   = pass show disroot
outgoing-cred-cmd = pass show disroot
