[mgr]
show_hidden = true

[opener]
zathura = [
    { run = 'zathura "$@"', orphan = true, desc = "Zathura", for = "unix" }
]

[open]
prepend_rules = [
    { mime = "application/pdf", use = "zathura" }
]
